name: Deploy Documentation

on: push

jobs:
  deploy_docs:
    name: Generate and Deploy Docs
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          doxygen --version

      - name: Generate Docs
        run: |
          doxygen
          cd docs
          ls -al
          cd
          pwd

      - name: Deploy Docs
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: 'deploy'

      - name: Check
        run: |
          cd deploy
          ls -la
          git branch -v

    # # checkout python
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'
    # # checkout ci-arduino in specific folder (ci)
    # - uses: actions/checkout@v3
    #   with:
    #     repository: adafruit/ci-arduino
    #     path: ci
    # - name: Build and Deploy Docs
    #   env:
    #     GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
    #     PRETTYNAME: "THIS IS A TEST"
    #   run: bash ci/doxy_gen_and_deploy.sh

