name: Deploy Documentation

on: push

jobs:
  deploy_docs:
    name: Fancy Name
    runs-on: ubuntu-latest
    steps:
    # checkout the repo so actions can run on it
      - name: Checkout Repo
        uses: actions/checkout@v3
    # install doxygen
      - name: Install Doxygen
        run:
          - sudo apt-get update
          - sudo apt-get install doxygen
          - doxygen --version
    # # checkout python
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'
    # # checkout ci-arduino in specific folder (ci)
    # - uses: actions/checkout@v3
    #   with:
    #     repository: adafruit/ci-arduino
    #     path: ci
    # - name: Build and Deploy Docs
    #   env:
    #     GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
    #     PRETTYNAME: "THIS IS A TEST"
    #   run: bash ci/doxy_gen_and_deploy.sh

